/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadora;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {
    Calculadora c;
    @BeforeEach void setup() {
        c = new Calculadora();
    }
    
    @Test void sumar() {
        assertEquals(5, c.sumar(2, 3));
    }

    @Test void multiplicar() {
        assertEquals(6, c.multiplicar(2, 3));
        assertEquals(20, c.multiplicar(5, 4));
    }
}
