/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadora;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {
    Calculadora c;
    @BeforeEach void setup() {
        c = new Calculadora();
    }
    
    @Test void sumar() {
        assertEquals(5, c.sumar(2, 3));
    }

    @Test void multiplicar() {
        assertEquals(6, c.multiplicar(2, 3));
        assertEquals(20, c.multiplicar(5, 4));
    }

    @Test void restar() {
        assertEquals(2, c.restar(3, 1));
        assertEquals(3, c.restar(10, 7));
    }

    @Test void dividir() {
        assertEquals(12/4, c.dividir(12, 4));
        assertEquals(0.5, c.dividir(1.0, 2.0));
    }
}
